status = [
  "check-cabal-files",
  "ci/hydra-build:x86_64-linux.pr.required",
  "ci/hydra-build:x86_64-darwin.pr.required",
  "ci/hydra-build:aarch64-darwin.pr.required",
]
timeout_sec = 7200
required_approvals = 1
block_labels = [ "WIP", "DO NOT MERGE" ]
delete_merged_branches = true
