- title: 'workbench:  updates'
  author: Kosyrev Serge
  url: https://github.com/input-output-hk/cardano-node/pull/5065
  number: 5065
  mergedAt: "2023-04-12T00:59:51Z"
  include: undecided
  files:
    - .gitignore
    - Makefile
    - bench/locli/locli.cabal
    - bench/locli/src/Cardano/Analysis/API.hs
    - bench/locli/src/Cardano/Analysis/API/Types.hs
    - bench/locli/src/Cardano/Analysis/BlockProp.hs
    - bench/locli/src/Cardano/Analysis/Summary.hs
    - bench/locli/src/Cardano/Command.hs
    - bench/locli/src/Cardano/Render.hs
    - bench/locli/src/Cardano/Unlog/LogObject.hs
    - bench/locli/src/Cardano/Util.hs
    - bench/locli/src/Data/CDF.hs
    - bench/locli/src/Data/Profile.hs
    - bench/workbench.gnuplot
    - configuration/cardano/membench-config-new.yaml
    - lib.mk
    - nix/haskell.nix
    - nix/nixos/cardano-node-service.nix
    - nix/pkgs.nix
    - nix/workbench/analyse/analyse.sh
    - nix/workbench/backend/runner.nix
    - nix/workbench/ede/chart.ede
    - nix/workbench/lib-cabal.sh
    - nix/workbench/profile/prof1-variants.jq
    - nix/workbench/profile/profile-run.jq
    - nix/workbench/profile/profile.nix
    - nix/workbench/service/generator.nix
    - nix/workbench/service/nodes.nix
    - nix/workbench/service/tracing.nix
    - nix/workbench/shell.nix
    - nix/workbench/wb
- title: Fix byron-to-alonzo/mkfiles.sh script for conway
  author: John Ky
  url: https://github.com/input-output-hk/cardano-node/pull/4972
  number: 4972
  mergedAt: "2023-03-13T11:28:13Z"
  notes: Add conwaya genesis script
  include: true
  files:
    - configuration/cardano/shelley_qa-conway-genesis.json
    - scripts/byron-to-alonzo/mkfiles.sh
- title: Take all dependencies from Hackage or CHaP
  author: Erik de Castro Lopo
  url: https://github.com/input-output-hk/cardano-node/pull/4921
  number: 4921
  mergedAt: "2023-03-10T00:20:06Z"
  notes: Add conway related configuration files
  include: true
  files:
    - .gitattributes
    - .github/workflows/check-mainnet-config.yml
    - bench/locli/locli.cabal
    - bench/locli/src/Cardano/Unlog/LogObject.hs
    - bench/locli/src/Data/CDF.hs
    - bench/tx-generator/src/Cardano/Benchmarking/GeneratorTx/NodeToNode.hs
    - bench/tx-generator/src/Cardano/Benchmarking/GeneratorTx/SizedMetadata.hs
    - bench/tx-generator/src/Cardano/Benchmarking/GeneratorTx/SubmissionClient.hs
    - bench/tx-generator/src/Cardano/Benchmarking/Script/Core.hs
    - bench/tx-generator/src/Cardano/TxGenerator/Setup/NodeConfig.hs
    - bench/tx-generator/src/Cardano/TxGenerator/Tx.hs
    - bench/tx-generator/src/Cardano/TxGenerator/Utils.hs
    - bench/tx-generator/tx-generator.cabal
    - cabal.project
    - cardano-api/cardano-api.cabal
    - cardano-api/gen/Test/Gen/Cardano/Api/Typed.hs
    - cardano-api/src/Cardano/Api.hs
    - cardano-api/src/Cardano/Api/Block.hs
    - cardano-api/src/Cardano/Api/Convenience/Constraints.hs
    - cardano-api/src/Cardano/Api/Eras.hs
    - cardano-api/src/Cardano/Api/Fees.hs
    - cardano-api/src/Cardano/Api/InMode.hs
    - cardano-api/src/Cardano/Api/LedgerState.hs
    - cardano-api/src/Cardano/Api/Modes.hs
    - cardano-api/src/Cardano/Api/Orphans.hs
    - cardano-api/src/Cardano/Api/Protocol.hs
    - cardano-api/src/Cardano/Api/ProtocolParameters.hs
    - cardano-api/src/Cardano/Api/Query.hs
    - cardano-api/src/Cardano/Api/Script.hs
    - cardano-api/src/Cardano/Api/SerialiseLedgerCddl.hs
    - cardano-api/src/Cardano/Api/Tx.hs
    - cardano-api/src/Cardano/Api/TxBody.hs
    - cardano-api/src/Cardano/Api/Utils.hs
    - cardano-api/test/Test/Cardano/Api/Json.hs
    - cardano-cli/cardano-cli.cabal
    - cardano-cli/src/Cardano/CLI/Shelley/Commands.hs
    - cardano-cli/src/Cardano/CLI/Shelley/Orphans.hs
    - cardano-cli/src/Cardano/CLI/Shelley/Parsers.hs
    - cardano-cli/src/Cardano/CLI/Shelley/Run/Genesis.hs
    - cardano-cli/src/Cardano/CLI/Shelley/Run/Query.hs
    - cardano-cli/test/Test/Golden/Shelley/Genesis/Create.hs
    - cardano-cli/test/data/golden/conway/genesis.conway.spec.json
    - cardano-cli/test/data/golden/shelley/genesis.conway.spec.json
    - cardano-client-demo/cardano-client-demo.cabal
    - cardano-node-chairman/cardano-node-chairman.cabal
    - cardano-node/cardano-node.cabal
    - cardano-node/src/Cardano/Node/Configuration/Logging.hs
    - cardano-node/src/Cardano/Node/Configuration/POM.hs
    - cardano-node/src/Cardano/Node/Orphans.hs
    - cardano-node/src/Cardano/Node/Parsers.hs
    - cardano-node/src/Cardano/Node/Protocol.hs
    - cardano-node/src/Cardano/Node/Protocol/Byron.hs
    - cardano-node/src/Cardano/Node/Protocol/Cardano.hs
    - cardano-node/src/Cardano/Node/Protocol/Conway.hs
    - cardano-node/src/Cardano/Node/Protocol/Shelley.hs
    - cardano-node/src/Cardano/Node/Startup.hs
    - cardano-node/src/Cardano/Node/Tracing/Documentation.hs
    - cardano-node/src/Cardano/Node/Tracing/StateRep.hs
    - cardano-node/src/Cardano/Node/Tracing/Tracers.hs
    - cardano-node/src/Cardano/Node/Tracing/Tracers/BlockReplayProgress.hs
    - cardano-node/src/Cardano/Node/Tracing/Tracers/ChainDB.hs
    - cardano-node/src/Cardano/Node/Tracing/Tracers/Consensus.hs
    - cardano-node/src/Cardano/Node/Tracing/Tracers/NodeToNode.hs
    - cardano-node/src/Cardano/Node/Tracing/Tracers/P2P.hs
    - cardano-node/src/Cardano/Node/Tracing/Tracers/Peer.hs
    - cardano-node/src/Cardano/Node/Tracing/Tracers/Startup.hs
    - cardano-node/src/Cardano/Node/Types.hs
    - cardano-node/src/Cardano/Tracing/OrphanInstances/Consensus.hs
    - cardano-node/src/Cardano/Tracing/OrphanInstances/Network.hs
    - cardano-node/src/Cardano/Tracing/Peer.hs
    - cardano-node/src/Cardano/Tracing/Tracers.hs
    - cardano-submit-api/cardano-submit-api.cabal
    - cardano-testnet/cardano-testnet.cabal
    - cardano-testnet/src/Testnet/Babbage.hs
    - cardano-testnet/src/Testnet/Cardano.hs
    - cardano-testnet/src/Testnet/Options.hs
    - cardano-testnet/src/Testnet/Shelley.hs
    - cardano-tracer/cardano-tracer.cabal
    - cardano-tracer/src/Cardano/Tracer/Acceptors/Client.hs
    - cardano-tracer/src/Cardano/Tracer/Acceptors/Server.hs
    - cardano-tracer/test/Cardano/Tracer/Test/Forwarder.hs
    - configuration/cardano/mainnet-config.json
    - configuration/cardano/mainnet-config.yaml
    - configuration/cardano/mainnet-conway-genesis.json
    - configuration/chairman/byron-shelley/configuration.yaml
    - flake.lock
    - scripts/babbage/conway-babbage-test-genesis.json
    - scripts/babbage/mkfiles.sh
    - trace-dispatcher/src/Cardano/Logging/Forwarding.hs
    - trace-dispatcher/trace-dispatcher.cabal
    - trace-forward/trace-forward.cabal
- title: Update docs
  author: 'Carlos LopezDeLara '
  url: https://github.com/input-output-hk/cardano-node/pull/4382
  number: 4382
  mergedAt: "2022-08-25T03:31:07Z"
  notes: Update README for where to download configurations from
  include: true
  files:
    - configuration/readme.md
    - doc/getting-started/cli.md
    - doc/logging-monitoring/logging.md
    - doc/stake-pool-operations/0_core_relay.md
    - doc/stake-pool-operations/10_query_stakepool.md
    - doc/stake-pool-operations/11_withdraw-rewards.md
    - doc/stake-pool-operations/12_retire_stakepool.md
    - doc/stake-pool-operations/1_getConfigFiles_AND_Connect.md
    - doc/stake-pool-operations/2_start_your_nodes.md
    - doc/stake-pool-operations/3_keys_and_addresses.md
    - doc/stake-pool-operations/4_simple_transaction.md
    - doc/stake-pool-operations/5_register_key.md
    - doc/stake-pool-operations/6_node_keys.md
    - doc/stake-pool-operations/7_KES_period.md
    - doc/stake-pool-operations/8_register_stakepool.md
    - doc/stake-pool-operations/9_leadership_schedule.md
- title: Minimise config
  author: Jürgen Nicklisch
  url: https://github.com/input-output-hk/cardano-node/pull/4351
  number: 4351
  mergedAt: "2022-09-21T21:14:30Z"
  notes: Edit trace options in configuration
  include: true
  files:
    - Makefile
    - README.rst
    - bench/locli/doc/Block propagation analysis data flow.graphml
    - bench/locli/doc/Machine performance analysis data flow.graphml
    - bench/locli/locli.cabal
    - bench/locli/src/Cardano/Analysis/API.hs
    - bench/locli/src/Cardano/Analysis/BlockProp.hs
    - bench/locli/src/Cardano/Analysis/ChainFilter.hs
    - bench/locli/src/Cardano/Analysis/Ground.hs
    - bench/locli/src/Cardano/Analysis/MachPerf.hs
    - bench/locli/src/Cardano/Analysis/Run.hs
    - bench/locli/src/Cardano/Command.hs
    - bench/locli/src/Cardano/Org.hs
    - bench/locli/src/Cardano/Render.hs
    - bench/locli/src/Cardano/Unlog/LogObject.hs
    - bench/locli/src/Cardano/Unlog/Resources.hs
    - bench/locli/src/Cardano/Util.hs
    - bench/locli/src/Data/CDF.hs
    - bench/locli/src/Data/DataDomain.hs
    - bench/locli/test/Test/Analysis/CDF.hs
    - bench/locli/test/Test/Unlog/Org.hs
    - bench/workbench.gnuplot
    - cardano-node/cardano-node.cabal
    - cardano-node/src/Cardano/Node/Tracing/API.hs
    - cardano-node/src/Cardano/Node/Tracing/DefaultTraceConfig.hs
    - cardano-node/src/Cardano/Node/Tracing/Documentation.hs
    - cardano-node/src/Cardano/Node/Tracing/Tracers.hs
    - cardano-node/src/Cardano/Node/Tracing/Tracers/Consensus.hs
    - cardano-tracer/src/Cardano/Tracer/Handlers/RTView/UI/Charts.hs
    - configuration/cardano/mainnet-config-new-tracing.yaml
    - doc/New Tracing Quickstart.md
    - doc/new-tracing/tracers_doc_generated.md
    - nix/workbench/analyse.sh
    - nix/workbench/backend/supervisor-run.nix
    - nix/workbench/chain-filters/base-k10.json
    - nix/workbench/chain-filters/base.json
    - nix/workbench/chain-filters/epoch3+.json
    - nix/workbench/chain-filters/model.json
    - nix/workbench/chain-filters/size-0.6.json
    - nix/workbench/chain-filters/size-mid.json
    - nix/workbench/chain-filters/unitary.json
    - nix/workbench/chaindb.sh
    - nix/workbench/genesis.sh
    - nix/workbench/lib-cabal.sh
    - nix/workbench/lib.sh
    - nix/workbench/manifest.sh
    - nix/workbench/profile.sh
    - nix/workbench/profiles/node-services.nix
    - nix/workbench/profiles/prof0-defaults.jq
    - nix/workbench/profiles/prof1-variants.jq
    - nix/workbench/profiles/prof2-derived.jq
    - nix/workbench/profiles/tracing-legacy.nix
    - nix/workbench/profiles/tracing.nix
    - nix/workbench/run.sh
    - nix/workbench/scenario.sh
    - nix/workbench/topology.sh
    - nix/workbench/wb
    - scripts/benchmarking/lib-node.sh
    - scripts/benchmarking/lib.sh
    - trace-dispatcher/doc/trace-dispatcher.md
    - trace-dispatcher/src/Cardano/Logging/ConfigurationParser.hs
    - trace-dispatcher/src/Cardano/Logging/Types.hs
- title: Rename TestEnableDevelopmentHardForkEras and TestEnableDevelopmentNetworkProtocols
  author: Robert 'Probie' Offner
  url: https://github.com/input-output-hk/cardano-node/pull/4341
  number: 4341
  mergedAt: "2023-04-11T06:51:26Z"
  include: true
  files:
    - cardano-api/ChangeLog.md
    - cardano-node/src/Cardano/Node/Configuration/POM.hs
    - cardano-node/src/Cardano/Node/Parsers.hs
    - cardano-node/src/Cardano/Node/Protocol/Cardano.hs
    - cardano-node/src/Cardano/Node/Run.hs
    - cardano-node/src/Cardano/Node/Startup.hs
    - cardano-node/src/Cardano/Node/Types.hs
    - cardano-node/test/Test/Cardano/Node/POM.hs
    - cardano-testnet/src/Testnet/Babbage.hs
    - cardano-testnet/src/Testnet/Cardano.hs
    - configuration/chairman/byron-shelley/configuration.yaml
    - nix/nixos/cardano-node-service.nix
    - nix/workbench/backend/nixops.nix
    - nix/workbench/backend/nixops/role-explorer.nix
    - nix/workbench/service/nodes.nix
    - scripts/babbage/mkfiles.sh
    - scripts/byron-to-alonzo/mkfiles.sh
