name: Check nix configuration

on:
  push:

jobs:
  check-for-doc-only-changes:
    runs-on: ubuntu-latest

    outputs:
        should_skip: ${{ steps.skip_check.outputs.should_skip }}

    steps:
    - name: Check if only documentation changes
      id: skip_check
      uses: fkirc/skip-duplicate-actions@v5
      with:
        paths_ignore: '["**/*.md", "**/*.rst", "**/LICENSE", "**/NOTICE"]'

    - name: Result
      run: |
        echo "should_skip: ${{ steps.skip_check.outputs.should_skip }}"

        echo "reason: ${{ steps.skip_check.outputs.reason }}"

        echo "== skipped_by =="
        cat <<EOF
        ${{ steps.skip_check.outputs.skipped_by }}
        EOF

        echo "== paths_result =="
        cat <<EOF
        ${{ steps.skip_check.outputs.paths_result }}
        EOF

        echo "== changed_files =="
        cat <<EOF
        ${{ steps.skip_check.outputs.changed_files }}
        EOF

  build:
    needs: check-for-doc-only-changes
    if: needs.check-for-doc-only-changes.outputs.should_skip != 'true'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - name: Install Nix
      uses: cachix/install-nix-action@v18
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          experimental-features = nix-command flakes
          allow-import-from-derivation = true
          substituters = https://cache.nixos.org https://hydra.iohk.io
          trusted-public-keys = iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

    - uses: actions/checkout@v2

    - name: Regenerate nix files
      run: |
        ./nix/regenerate.sh

    - name: Check nix configuration differences
      run: |
        git diff --exit-code
