name: Nightly Trigger

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 5 * * *'

jobs:
  check-for-doc-only-changes:
    outputs:
        should_skip: ${{ steps.skip_check.outputs.should_skip }}

    steps:
    - name: Check if only documentation changes
      id: skip_check
      uses: fkirc/skip-duplicate-actions@v5
      with:
        paths_ignore: '["**/*.md", "**/*.rst", "**/LICENSE", "**/NOTICE"]'

    - name: Result
      run: |
        echo "should_skip: ${{ steps.skip_check.outputs.should_skip }}"

        echo "reason: ${{ steps.skip_check.outputs.reason }}"

        echo "== skipped_by =="
        cat <<EOF
        ${{ steps.skip_check.outputs.skipped_by }}
        EOF

        echo "== paths_result =="
        cat <<EOF
        ${{ steps.skip_check.outputs.paths_result }}
        EOF

        echo "== changed_files =="
        cat <<EOF
        ${{ steps.skip_check.outputs.changed_files }}
        EOF

  build:
    needs: check-for-doc-only-changes
    if: needs.check-for-doc-only-changes.outputs.should_skip != 'true'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - uses: actions/checkout@v2

    - name: Tag
      run: |
        git branch -D nightly || true
        git checkout -b nightly
        git push origin nightly --force

    - name: Invoke workflow
      uses: input-output-hk/workflow-dispatch@v1
      with:
        workflow: .github/workflows/haskell.yml
        ref: nightly
        token: ${{ secrets.MACHINE_TOKEN }}
        inputs: '{ "reason": "nightly", "tests": "all" }'
