name: Post Release Upload
# Uploads the macOS, win64 and linux binary packages as github artifacts
# These can be accessed by:
# * Going to https://github.com/input-output-hk/cardano-node/actions/workflows/release-upload.yaml
# * Selecting a run
# The Artifacts should be listed at the bottom.
#
# Even though the artifacts themselves are compressed (.tar.gz and .zip files),
# the action/uppload-artifact puts each in its own .zip.
on:
  release:
    types:
      - published
  push:
    tags:
      - '**'

jobs:
  upload:
    name: "Upload Artifacts"
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux
          - win64
          - macos

    runs-on: ${{ matrix.platform == 'macos' && 'macos-latest' || 'ubuntu-latest' }}
    steps:
      - name: Install Nix with good defaults
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= loony-tools:pr9m4BkM/5/eSTZlkQyRt57Jz7OMBxNSUiMC4FkcNfk=
            substituters = https://cache.iog.io/ https://cache.zw3rk.com/ https://cache.nixos.org/
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Checkout repository
        uses: actions/checkout@v3
      # We copy the file out of `result/` as `upload-artifact` does
      # not like to upload files from links (complains that `result`
      # is not a directory).
      - name: Build
        run: |
          nix build .#hydraJobs.${{
               matrix.platform == 'macos' && 'native'
            || matrix.platform == 'win64' && 'windows'
            || 'musl' }}.cardano-node-${{matrix.platform}}
          cp result/cardano-node-* .
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: cardano-node-${{matrix.platform}}
          path: cardano-node-*-${{matrix.platform}}.${{ matrix.platform == 'win64' && 'zip' || 'tar.gz' }}
