name: Post Release Upload
# This makes it easy to get download release binaries built using
# a github action for any tagged commit.
#
# This workflow builds and uploads the macOS, win64 and linux
# binary packages as github artifacts.
#
# These can be accessed by:
# * Going to https://github.com/input-output-hk/cardano-node/actions/workflows/release-upload.yaml
# * Selecting a run
# The Artifacts should be listed at the bottom.
#
# Even though the artifacts themselves are compressed (.tar.gz and .zip files),
# the action/uppload-artifact puts each in its own .zip.
#
# The artifacts are then downloaded and uploaded to as release assets
on:
  release:
    types:
      - published
  push:
    tags:
      - '**'

jobs:
  build:
    name: "Build Artifacts"
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux
          - win64
          - macos

    runs-on:
      - self-hosted
      - ${{ matrix.platform == 'macos' && 'macOS' || 'Linux' }}
      - X64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Remove old artifacts
        run: rm cardano-node-*
      # We copy the file out of `result/` as `upload-artifact` does
      # not like to upload files from links (complains that `result`
      # is not a directory).
      - name: Build
        run: |
          nix build .#hydraJobs.${{
               matrix.platform == 'macos' && 'native'
            || matrix.platform == 'win64' && 'windows'
            || 'musl' }}.cardano-node-${{matrix.platform}}
          cp result/cardano-node-* .
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: cardano-node-${{matrix.platform}}
          path: cardano-node-*-${{matrix.platform}}.${{ matrix.platform == 'win64' && 'zip' || 'tar.gz' }}
  upload:
    name: "Upload Assets"
    needs: build
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Remove old artifacts
        run: rm cardano-node-*
      - name: Download win64
        uses: actions/download-artifact@v3
        with:
          name: cardano-node-win64
      - name: Download macos
        uses: actions/download-artifact@v3
        with:
          name: cardano-node-macos
      - name: Download linux
        uses: actions/download-artifact@v3
        with:
          name: cardano-node-linux
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: cardano-node-*
